image: node:18

pages:
  stage: deploy
  before_script:
    - npm ci
    - npm run build
  script:
    - mkdir -p public
    - cp -r dist/* public/
    - cp dist/index.html public/404.html  # Optional for SPAs like React/Vite
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
