// src/models/RoleType.ts
export enum RoleType {
    VIEW_WILL = "VIEW_WILL",
    CREATE_WILL = "CREATE_WILL",
    VALIDATE_WILL = "VALIDATE_WILL",
    MANAGE_USERS = "MANAGE_USERS",
    UPLOAD_EMPLOYEES = "UPLOAD_EMPLOYEES",
    VIEW_DASHBOARD = "VIEW_DASHBOARD",
    SUPER_ADMIN = "SUPER_ADMIN",
}
