// src/models/UserType.ts
export enum UserType {
    INDIVIDUAL_USER = "INDIVIDUAL_USER",
    CORPORATE_ADMIN = "CORPORATE_ADMIN",
    EMPLOYEE_USER = "EMPLOYEE_USER",
    LEGAL_PARTNER = "LEGAL_PARTNER",
    TECH_PARTNER = "TECH_PARTNER",
    SUPPORT_USER = "SUPPORT_USER",
    SUPER_ADMIN = "SUPER_ADMIN",
}
